"""Mako template placeholder for Alembic autogenerated scripts.
This file is intentionally minimal; Alembic will create revision files.
"""

from alembic import op
import sqlalchemy as sa

revision = '${up_revision}'
down_revision = ${repr(down_revision)}
branch_labels = ${repr(branch_labels)}
depends_on = ${repr(depends_on)}

def upgrade():
    pass

def downgrade():
    pass
